baselines
baseline01: spec
	<version: '0.1-baseline'>

	spec for: #'common' do: [
		spec blessing: #'baseline'.
		spec repository: 'gitfiletree://C:\Utilisateurs\a577142\Documents\Pharo images\Moose Jenkins-moose-6.0-#105-moose-6.0.zip- Hackathon\HackathonSattose2015 master'.
		spec project: 'Spy2' with: [
				spec
					className: #ConfigurationOfSpy2;
					versionString: #'stable';
					repository: 'http://smalltalkhub.com/mc/ObjectProfile/Spy2/main/' ].
		spec package: 'Hackathon'. ].
